services:
  mariadb:
    image: zmutclik/mariadb:latest
    container_name: ${CONTAINER_NAME}-db
    hostname: ${HOSTNAME}db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOTPASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - data:/var/lib/mysql
    networks:
      net:
#       ipv4_address: ${DB_HOST}
    dns:
      - ${DNS1}
      - ${DNS2}
  web:
    image: zmutclik/webapache:${PHPVERSION}
    environment:
      - SERVERNAME=${SERVERNAME}
      - PHPVERSION=${PHPVERSION}
      - DOCUMENTROOT=${DOCUMENTROOT}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_APPUSER}
      - DB_PASS=${DB_APPPASS}
      - DB_NAME=${DB_NAME}
    container_name: ${CONTAINER_NAME}
    hostname: ${HOSTNAME}
    restart: always
    volumes:
     - datawww:/var/www/html
    ports:
      - "${APP_PORT}:80/tcp"
    dns:
      - ${DNS1}
      - ${DNS2}
    depends_on:
      - mariadb

volumes:
  datawww:
#    driver_opts:
#      type: nfs
#      o: addr=${NFS_ADDRESS},nfsvers=4
#      device: ${NFS_APP_PATH}
  data:
#    driver_opts:
#      type: nfs
#      o: addr=${NFS_ADDRESS},nfsvers=4
#      device: ${NFS_DB_PATH}
