services:
  mariadb:
    image: zmutclik/mariadb:latest
    container_name: ${CONTAINER_NAME}-db
    hostname: ${HOSTNAME}db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOTPASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_APPUSER}
      MARIADB_PASSWORD: ${DB_APPPASS}
    ports:
      - "${DATA_PORT}:3306"
    volumes:
      - data:/var/lib/mysql
    networks:
      net:
    dns:
      - ${DNS1}
      - ${DNS2}
  web:
    image: zmutclik/webapache:${PHPVERSION}
    environment:
      - SERVERNAME=${SERVERNAME}
      - PHPVERSION=${PHPVERSION}
      - DOCUMENTROOT=${DOCUMENTROOT}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_APPUSER}
      - DB_PASS=${DB_APPPASS}
      - DB_NAME=${DB_NAME}
    container_name: ${CONTAINER_NAME}
    hostname: ${HOSTNAME}
    restart: always
    volumes:
     - datawww:/var/www/html
    ports:
      - "${APPS_PORT}:80/tcp"
    dns:
      - ${DNS1}
      - ${DNS2}
    networks:
      net:
    depends_on:
      - mariadb
  webhook:
    image: zmutclik/git_webhook:latest
    container_name: ${CONTAINER_NAME}_webhook
    ports:
      - "${HOOK_PORT}:8000"
    volumes:
      - repository:/app/repository
      - secrets:/app/secrets
      - logs:/app/logs
    environment:
      - BRANCH=${BRANCH}
      - REPO_PATH=${REPO_PATH}
      - GIT_URL_SSH=${GIT_URL_SSH}
    restart: always
    dns:
      - ${DNS1}
      - ${DNS2}
    networks:
      net:
    depends_on:
      - mariadb
      - web

networks:
  net:

volumes:
  datawww:
#    driver_opts:
#      type: nfs
#      o: addr=${NFS_ADDRESS},nfsvers=4
#      device: ${NFS_APPS_PATH}
  data:
#    driver_opts:
#      type: nfs
#      o: addr=${NFS_ADDRESS},nfsvers=4
#      device: ${NFS_DATA_PATH}
  repository:
#    driver_opts:
#      type: nfs
#      o: addr=${NFS_ADDRESS},nfsvers=4
#      device: ${NFS_APPS_PATH}
  secrets:
  logs:
