services:
  web:
    image: zmutclik/webapache:${PHPVERSION}
    environment:
      - SERVERNAME=${SERVERNAME}
      - PHPVERSION=${PHPVERSION}
      - DOCUMENTROOT=${DOCUMENTROOT}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_APPUSER}
      - DB_PASS=${DB_APPPASS}
      - DB_NAME=${DB_NAME}
    container_name: ${CONTAINER_NAME}
    hostname: ${HOSTNAME}
    restart: always
    volumes:
     - datawww:/var/www/html
    ports:
      - "${APP_PORT}:80/tcp"
    dns:
      - ${DNS1}
      - ${DNS2}

volumes:
  datawww:
#    driver_opts:
#      type: nfs
#      o: addr=${NFS_ADDRESS},nfsvers=4
#      device: ${NFS_PATH}
