
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PHPVERSION=${PHPVERSION}
        - SERVERNAME=${SERVERNAME}
    env_file:
      - stack.env
    container_name: ${CONTAINER_NAME}
    hostname: ${HOSTNAME}
    restart: always
    volumes:
      - ./www:/var/www/html
#      - webapp:/var/www/html
#      - ./boot.sh:/boot/start.sh
      - ./virtualhost.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "${APP_PORT}:80/tcp"
    networks:
      net:
#        ipv4_address: ${IPv4}
    dns:
      - ${DNS1}
      - ${DNS2}
    entrypoint: |
      bash -c "
      /etc/init.d/cron start &&
      source /etc/apache2/envvars &&
      exec apache2 -D FOREGROUND"

networks:
  net:
#    name: ${NETWORK}
#    external: true
#    ipam:
#      config:
#        - subnet: ${SUBNET}
#          gateway: ${GATEWAY}

#volumes:
#  webapp:
#    driver_opts:
#      type: nfs
#      o: addr=${NFS_ADDRESS},nfsvers=4
#      device: ${NFS_PATH}
