
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PHPVERSION=${PHPVERSION}
        - SERVERNAME=${SERVERNAME}
        - DB_HOST=${DB_HOST}
        - DB_USER=${DB_USER}
        - DB_PASS=${DB_PASS}
        - DB_NAME=${DB_NAME}
    environment:
      - SERVERNAME=${SERVERNAME}
      - PHPVERSION=${PHPVERSION}
      - DOCUMENTROOT=${DOCUMENTROOT}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    container_name: ${CONTAINER_NAME}
    hostname: ${HOSTNAME}
    restart: always
    volumes:
     - webapp:/var/www/html
    ports:
      - "${APP_PORT}:80/tcp"
#    networks:
#      net:
#        ipv4_address: ${IPv4}
#    dns:
#      - ${DNS1}
#      - ${DNS2}

#networks:
#  net:
#    name: ${NETWORK}
#    external: true
#    ipam:
#      config:
#        - subnet: ${SUBNET}
#          gateway: ${GATEWAY}

volumes:
  webapp:
#    driver_opts:
#      type: nfs
#      o: addr=${NFS_ADDRESS},nfsvers=4
#      device: ${NFS_PATH}
